capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('teaching/', include(('teaching.urls', 'teaching'), namespace='teaching')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# # Serve media files in development (DEBUG=False mode)
if not settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# if settings.DEBUG:  # Serve static files in production 
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

learning/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('student/dashboard/', StudentDashboardView.as_view(), name='student_dashboard'),

    path('quizzes/', QuizListView.as_view(), name='quizzes'),
    path('quiz-start/<int:quiz_id>/', QuizStartView.as_view(), name='quiz_start'),
    path('quiz-question/<int:quiz_id>/<int:question_order>/', QuizQuestionView.as_view(), name='quiz_question'),
    path('quiz-complete/<int:quiz_id>/', QuizCompleteView.as_view(), name='quiz_complete'),
    path('quiz-finalize/<int:quiz_id>/', FinalizeQuizView.as_view(), name='quiz_finalize'),

    path('new-notifications-count/', NewNotifCount.as_view(), name="new_notif_count"),
    path('mark-notifications-read/', MarkNotificationsRead.as_view(), name="mark_notifs_read"),
    path('notifications/', Notifications.as_view(), name='notifications'),
    
    path('lesson/<str:course_title>/<int:lesson_order>/', LessonView.as_view(), name='lesson'),
]

users/urls.py
from django.urls import path
from users.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', homepage_view, name="homepage"),
    path('accounts/login/', login_view, name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('register/', register, name="register"),
    path('courses/', courses, name='courses'),
    path('course_details/<int:course_id>/', course_details, name="course_details"),
    path('enroll/<int:course_id>/', enroll, name="enroll"),
]

learning/models.py
from django.db import models

# Create your models here.

learning/views.py
from django.shortcuts import render, redirect
from users.models import *
from django.views.generic import TemplateView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse, JsonResponse
from users.utils import send_notification
from django.utils.timezone import now
from datetime import datetime
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
import json
from django.urls import reverse_lazy

#-----------------------------------------------------------
# Mixins
#-----------------------------------------------------------
class RoleRequiredMixin(LoginRequiredMixin):
    """
    Is used to check the required role of the user 
    and redirect unauthorized user to the login page.
    """
    required_role = None  # Specify the required role later in the view
    login_url = reverse_lazy('login') # Redirect unauthorized user to login page
    
    def dispatch(self, request, *args, **kwargs):
        # ensure the user is authenticated (LoginRequiredMixin handles this)
        if not request.user.is_authenticated:
            return super().dispatch(request, *args, **kwargs)  # This will redirect to the login page

        # Then check the user's role
        if not self.has_required_role():
            return HttpResponseForbidden("You don't have the required role to access this page.")
        
        return super().dispatch(request, *args, **kwargs)

    # def has_required_role(self):
    #     return self.request.user.profile.role == self.required_role

    def has_required_role(self):
    # Ensure the user's profile and role attribute exist
        return getattr(self.request.user.profile, 'role', None) == self.required_role


class StudentEnrollmentMixin:
    def get_enrolled_courses(self):
        student_profile = self.request.user.profile
        # Using select_related() to reduce the amount of database queries
        return Enrollment.objects.filter(student=student_profile).select_related('course')
    

#-----------------------------------------------------------
# Student-related views
#-----------------------------------------------------------

class StudentDashboardView(RoleRequiredMixin, StudentEnrollmentMixin, TemplateView):
    """
    Handles the student's dashboard view, providing course progress.

    GET: Displays the dashboard for students, showing an overview of their 
    enrolled courses, progress, and relevant data. This view extends `TemplateView` 
    and enforces role-based access control using mixins.

    POST: (For testing purposes) Demonstrates how `WebSocket.onmessage` can trigger 
    live notification updates for the current user without requiring a page reload.
    """
    template_name = 'learning/student_dashboard.html'
    required_role = 'student'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        enrolled_courses = self.get_enrolled_courses()
        student = self.request.user.profile
        
        context["course_progress_data"] = [
            {
                'course': enrollment.course.title,
                'progress': enrollment.calculate_progress(),
                'last_accessed_lesson_order': enrollment.get_last_accessed_lesson_order(),
                'last_accessed_lesson': Lesson.objects.get(course=enrollment.course,
                                                           order=enrollment.get_last_accessed_lesson_order()),
                'completed_assignments': StudentAssignment.objects.filter(course=enrollment.course, student=student, 
                                                                          handed_in=True).order_by('-date_handed_in'),
                'average_grade': enrollment.calculate_average_grade(),
            }
            for enrollment in enrolled_courses
        ]
        return context
    

    def post(self, request, *args, **kwargs):
        # Create a test notification for current user
        notification = Notification.objects.create(
            sender=None,
            message=f"Notification is test",
        )
        # Add the current user's profile as the recipient
        notification.recipient.add(self.request.user.profile)
        notification.save()
        send_notification(notification) # Call for helper function
        
        # Return a JSON response indicating success
        return JsonResponse({'status': 'success', 'message': 'Notification created successfully.'})


class Notifications(View):
    """
    Returns the latest notifications in JSON format for the 
    StudentDashboardView to allow real-time updates via JavaScript.
    """
    def get(self, request, *args, **kwargs):
        # Get the notifications for the current user
        student = request.user.profile
        notifications = Notification.objects.filter(recipient=student).order_by('-timestamp')

        # Serialize the notifications to send as JSON
        notifications_data = [
            {
                'message': notif.message,
                'timestamp': notif.timestamp.strftime('%Y-%m-%d %H:%M:%S'),
            }
            for notif in notifications
        ]

        return JsonResponse({
            'notifications': notifications_data,
        })


class NewNotifCount(RoleRequiredMixin, View):
    """
    Returns the count of unread notifications for the current user 
    in JSON format to support real-time updates in the UI.
    """
    required_role = 'student'

    def get(self, request, *args, **kwargs):
        student = self.request.user.profile

        # Get the count of new notifications for the current student
        count = Notification.objects.filter(recipient=student, is_read=False).count()
        
        return JsonResponse({'new_notifications_count': count})
    

class MarkNotificationsRead(View):
    """
    Marks all unread notifications as read for the current user.
    """
    def put(self, request, *args, **kwargs):
        student = self.request.user.profile
        # Update all unread notifications for the current student
        Notification.objects.filter(recipient=student, is_read=False).update(is_read=True)

        return JsonResponse({'success': 'True'})
    

class LessonView(RoleRequiredMixin, TemplateView):
    """
    View for rendering a specific lesson within a course for students,
    allows students to engage with course materials(watch video, read and download lesson contents) 
    and submit their assignments.

    Methods:
        - post: Handles the submission of assignments by students.
            Upon receiving an assignment file, it creates a StudentAssignment record,
            marks the lesson as complete in the LessonCompletion model, and redirects
            the user back to the lesson page.
            If no file is submitted, it redirects the user back to the lesson page without
            making changes.
    """
    template_name = 'learning/lesson.html'
    required_role = 'student'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Access the URL parameters from kwargs
        course_title = self.kwargs['course_title']
        lesson_order = self.kwargs['lesson_order']

        # Get the course and lesson based on the URL parameters
        course = get_object_or_404(Course, title=course_title)
        lesson = get_object_or_404(Lesson, order=lesson_order, course=course)
        student = self.request.user.profile

        # Query for previous and next lessons
        previous_lesson = Lesson.objects.filter(course=course, order=lesson.order - 1).first()
        next_lesson = Lesson.objects.filter(course=course, order=lesson.order + 1).first()

        # Add the course and lesson to the context
        context['course'] = course
        context['lesson'] = {
            'title': lesson.title,
            'order': lesson.order,
            'is_complete': LessonCompletion.objects.filter(enrollment__student=student, lesson=lesson, 
                                                           is_complete=True).exists(),
            'content': lesson.content,
            'video_file': lesson.video_file,
            'video_url': lesson.video_url,
            'homework_requirements': lesson.homework_requirements,
            'pdf': lesson.pdf,
            'previous_lesson_order': previous_lesson.order if previous_lesson else None,
            'next_lesson_order': next_lesson.order if next_lesson else None,
        }
        context['quizzes'] = Quiz.objects.filter(lesson=lesson)
        return context
    

    def post(self, request, course_title, lesson_order):
        # Handling the submission of assignments by students
        course = get_object_or_404(Course, title=course_title)
        lesson = get_object_or_404(Lesson, order=lesson_order, course=course)
        student = request.user.profile
        enrollment = get_object_or_404(Enrollment, student=student, course=course)

        # Check if an assignment file is included in the request
        if 'assignment' in request.FILES:
            assignment_file = request.FILES['assignment']

            # Validate the file type
            if not assignment_file.name.endswith('.pdf'):
                return HttpResponse("Invalid file type. Please upload a PDF file.", status=400)

            # Create and save the StudentAssignment object
            StudentAssignment.objects.create(student=student, lesson=lesson, course=course,
                                            file=assignment_file, handed_in=True)

            # Update completion status in LessonCompletion model
            LessonCompletion.objects.update_or_create(enrollment=enrollment, lesson=lesson,
                                                        defaults={'is_complete': True})

            return redirect('learning:lesson', course_title=course.title, lesson_order=lesson.order)
        

learning/templates/learning/lesson.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}"> 
{% endblock %}

{% block body %}
<body>
    <div class="container">
        <!-- Course and Lesson Info -->
        <div class="lesson-header">
            <h1>{{ course.title }}, Lesson {{ lesson.order }}:</h1>
            <h2> {{ lesson.title }}</h2>
        </div>

        {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}

        <!-- Lesson Completion Status -->
        <div class="completion-indicator">
            <span class="{% if lesson.is_complete %}complete{% else %}incomplete{% endif %}">
                {% if lesson.is_complete %}Lesson Completed{% else %}Lesson Incomplete{% endif %}
            </span>
        </div>

        <!-- Video Section -->
        <div class="lesson-video">
            {% if lesson.video_file %}
                <video controls>
                    <source src="{{ lesson.video_file.url }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            {% elif lesson.video_url %}
                <iframe width="1200" height="500" src="{{ lesson.video_url }}" frameborder="0" allowfullscreen></iframe>
            {% else %}
                <p>No video available for this lesson.</p>
            {% endif %}
        </div>

        <!-- Lesson Content -->
        <section class="lesson-content">
            <h3>Lesson Material</h3>
            <p>{{ lesson.content }}</p>
        </section>

        <!-- PDF Downloads -->
        <section class="lesson-pdfs">
        <h3>Downloadable PDF</h3>
        {% if lesson.pdf %}
            <ul>
                <li><a href="{{ lesson.pdf.url }}" download>{{ lesson.title }} - PDF</a></li>
            </ul>
        {% else %}
            <p>No downloadable PDF available for this lesson.</p>
        {% endif %}
        </section>

        <!-- Homework Section -->
        <section class="homework-section">
            <h3>Homework Requirements</h3>
            <p>{{ lesson.homework_requirements }}</p>

            <!-- Assignment Submission -->
            {% if lesson.is_complete %}
                <p>You have successfully submitted assignment for this lesson.</p>
            {% else %}
                <form action="" method="post" enctype="multipart/form-data" id="submission">
                    {% csrf_token %}
                    <label for="assignment">Submit Your Assignment:</label>
                    <input type="file" id="assignment" name="assignment">
                    <button type="submit">Submit</button>
                </form>
            {% endif %}
        </section>

        <!-- Quizzes Section -->
        <section class="section">
            <h3>Quizzes</h3>
            <div class="announcement">
                <ul>
                    {% for quiz in quizzes %}
                    <li class="enrolled-courses">
                        <a class="assignment" href="{% url 'learning:quiz_start' quiz_id=quiz.id %}">
                            {{ quiz.name }} ({{ quiz.difficulty }})
                        
                            {% if quiz.session.score %}
                                <div class="mini-info">
                                    - Completed ( Score: {{ quiz.session.score }}% )
                                </div>
                            {% endif %}
                        </a>
                    </li>
                    {% empty %}
                        <li>No quizzes available for this lesson yet.</li>
                    {% endfor %}
                </ul>
            </div>
        </section>

        <!-- Navigation between lessons -->
        <div class="center">
            <span class="one-line">
                {% if lesson.previous_lesson_order %}
                <!-- Previous Lesson Button -->
                <div class="next-lesson">
                    <a href="{% url 'learning:lesson' course_title=course.title lesson_order=lesson.previous_lesson_order%}" class="button">Previous Lesson</a>
                </div>
                {% endif %}
                <!-- Next Lesson Button -->
                {% if lesson.next_lesson_order %}
                <div class="next-lesson">
                    <a href="{% url 'learning:lesson' course_title=course.title lesson_order=lesson.next_lesson_order%}" class="button">Next Lesson</a>
                </div>
                {% endif %}
            </span>
        </div>
    </div>
</body>
{% endblock %}

learning/templates/learning/quiz_complete.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}"> 
{% endblock %}

{% block body %}
<body>
    <div class="container">
        <div class="question-card">
            <h2 class="question-title" id="question-title">You have completed this quiz.</h2>
            
                <ul>
                    <li><strong>Difficulty:</strong> {{ quiz.difficulty }}</li>
                    <li><strong>Course:</strong> {{ quiz.course.title }}</li>
                    <li><strong>Lesson:</strong> {{ quiz.lesson.title }}</li>
                    <li><strong>Required score to pass:</strong> {{ quiz.required_score }}%</li>
                    <hr>
                    <li><strong>Your score:</strong> {{ session.score }}% 
                        ( {{session.correct_answer_count }} / {{ quiz.questions.count }} correct answers )
                    </li>
                    <li><strong>{{ message }}</strong></li>
                    <li><strong>You solved this quiz in : </strong> 
                        {{ session_minutes }} min {{ session_seconds }} sec
                    </li>
                </ul>
                {% if session.passed %}
                    <h2 class="question-title" id="passed-flag">PASSED</h2>
                {% else %}
                    <h2 class="question-title" id="not-passed-flag">DID NOT PASS</h2>
                {% endif %}
        </div>

        <button id="toggleAnswers" class="toggle-button">View Correct Answers</button>
        <div id="answersTable" class="answers-table-container" style="display: none;">
            <table class="comparison-table">
                <thead>
                    <tr>
                        <th>Question</th>
                        <th>Your Answer</th>
                        <th>Correct Answer</th>
                        <th>Result</th>
                    </tr>
                </thead>
                <tbody>
                    {% for answer in submitted_answers %}
                    <tr>
                        <td>{{ answer.question.text }}</td>
                        <td>{{ answer.selected_answer }}</td>
                        <td>
                            {% for correct_answer in answer.question.options.all %}
                                {% if correct_answer.is_correct %}
                                    {{ correct_answer.text }}
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% if answer.is_correct %}
                                <span class="result correct">Correct</span>
                            {% else %}
                                <span class="result incorrect">Incorrect</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
{% endblock %}

learning/templates/learning/quiz_question.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}"> 
{% endblock %}

{% block body %}
<body>
    <div class="container">
        <div class="progress-container-quiz">
            <div class="progress-bar-quiz" style="width: {{ progress_percentage }}%;" id="progress-bar">{{ progress_percentage }}%</div>
        </div>

        <!-- Question Card -->
        <div class="question-card">
            <h2 class="question-title" id="question-title">{{ question }}</h2>

            <div class="timer" id="timer" data-time="{{ remaining_time }}">
                Time Remaining: <span id="time-display">{{ remaining_time|time:"H:i:s" }}</span>
            </div>
            
            
            {% if question.image %}
                <div class="image-container">
                    <img src="{{ question.image.url }}" alt="Quiz Image" class="quiz-image" loading="lazy">
                </div>
            {% endif %}

            <form id="question-form" method="POST" data-quiz-id="{{ quiz.id }}" 
            action="{% url 'learning:quiz_question' quiz_id=quiz.id question_order=question_order %}">
                {% csrf_token %}
                <!-- Answer Options -->
                <div class="options-container" id="options-container">
                    {% for option in question.options.all %}
                        <span class="inline">
                            <input class="quiz-input" type="radio" id="option{{ option.id }}" name="student_answer" value="{{ option.id }}">
                            <label for="option{{ option.id }}">{{ option.text }}</label>
                        </span>
                    {% endfor %}
                </div>
                <button type="submit" class="btn-next" id="next-button">Next Question</button>      
            </form>
            
        </div>
    </div>
    
<script>
let isFinalized = false;
// JavaScript to visually count down on the frontend
let timerElement = document.getElementById('timer');
let timeRemaining = parseInt(timerElement.getAttribute('data-time')); // Remaining seconds

function updateTimer() {
    if (timeRemaining <= 0 && !isFinalized) {
        isFinalized = true; // Prevent further requests
        fetch("/learning/quiz-finalize/{{ quiz.id }}/", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": document.querySelector('[name=csrfmiddlewaretoken]').value, 
            },
            body: JSON.stringify({
                quiz_id: "{{ quiz.id }}"
            }),
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                window.location.href = "/learning/quiz-complete/{{ quiz.id }}/"; // Redirect after finalization
            } else {
                alert("An error occurred while finalizing the quiz.");
            }
        });
        //return;
    }
    
    if (timeRemaining > 0) {
        timeRemaining--;
    }
    let minutes = Math.floor(timeRemaining / 60);
    let seconds = timeRemaining % 60;
    document.getElementById('time-display').textContent =
        `${minutes}:${seconds < 10 ? "0" : ""}${seconds}`;
}

setInterval(updateTimer, 1000); // Update every second

    </script>
</body>
{% endblock %}

learning/templates/learning/quiz_start.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}"> 
{% endblock %}

{% block body %}
<body>
    <h1 class="quiz-header">{{ quiz.name }}</h1>
    <div class="container">
        <section class="quiz-info section">
            <ul>
                <li><strong>Difficulty:</strong> {{ quiz.difficulty }}</li>
                <li><strong>Course:</strong> {{ quiz.course.title }}</li>
                <li><strong>Lesson:</strong> {{ quiz.lesson.title }}</li>
                <li><strong>Required score to pass:</strong> {{ quiz.required_score }}%</li>
                <li><strong>Timer will be set for:</strong> {{ quiz.time }} min</li>
            </ul>
        </section>
            {% if session_exists %}
                <p class="quiz-p">You have already taken this test quiz. Your score is {{ session.score }}%</p>
            {% else %}
                <p class="quiz-p">This is a test quiz session. You <strong>can not</strong> retake this test quiz.</p>
                <!--Use GET method to start the quiz and show the first question-->
                <div class="start">
                    <a href="{% url 'learning:quiz_question' quiz_id=quiz.id question_order=1 %}" class="btn">Start Quiz</a>
                </div>
            {% endif %}
    </div>
</body>
{% endblock %}

learning/templates/learning/quizzes.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}"> 
{% endblock %}

{% block body %}
<body>
    <div class="courses-header">
        <h1 class="header">Quizzes</h1>
    </div>
    <div class="container">
        {% for course in quizzes %}
            <section class="section">
                <h3>Course: {{ course.course_name }}</h3>
                <ul>
                    {% for item in course.quizzes %}
                    <li class="enrolled-courses">
                        <a class="assignment" href="{% url 'learning:quiz_start' quiz_id=item.quiz.id %}">
                            {{ item.quiz.name }} ({{ item.quiz.difficulty }})
                        
                            {% if item.session.score %}
                                <div class="mini-info">
                                    - Completed ( Score: {{ item.session.score }}% )
                                </div>
                            {% endif %}
                        </a>
                    </li>
                    {% empty %}
                        <li>No quizzes available for this course yet.</li>
                    {% endfor %}
                </ul>
            </section>
            
        {% endfor %}
    </div>
</body>
{% endblock %}

learning/templates/learning/student_dashboard.html
{% extends 'users/layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Dashboard</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}"> 
    {% endblock %}
</head>

{% block body %}
    <div class="courses-header">
        <h1 class="header">My Dashboard</h1>
    </div>
    <div class="container">
        <!-- Notifications Section -->
        <section class="section">
            <div id="notif-header" class="notification-header">
                <h3 class="notif">Notifications</h3>
                <!-- Notification Bell -->
                <a href="#" id="notificationBell">
                    <i id="bellCount" class="fa-solid fa-bell" data-count="0"></i>
                </a>
            </div>
            
            <div id="notif-messages" class="hidden" >
                <!-- JS Code -->
            </div>
            <button id="testNotificationButton">Create Test Notification</button>
        </section>

        <!-- Courses Enrolled Section -->
        <section class="section">
            <h3>Courses Enrolled</h3>
            <ul>
                {% for item in course_progress_data %}
                    <li class="enrolled-courses padding">
                        <div class="course-info">
                            <span>{{ item.course }}</span>
                        </div>
                        <div class="progress-info" id="wide">
                            <div class="progress-bar-container">
                                <div class="progress-bar" style="width: {{ item.progress }}%;"></div>
                            </div>
                            <span class="progress-text">{{ item.progress }}%</span>
                        </div>
                        <div class="last-accessed">
                            <p>Return to:   
                                <a href="{% url 'learning:lesson' course_title=item.course lesson_order=item.last_accessed_lesson_order %}">
                                    Last accessed lesson
                                </a>
                            </p>
                        </div>
                    </li>
                {% empty %}
                    <li>No enrolled courses.</li>
                {% endfor %}
            </ul>
        </section>
    
        <!-- Assignments Section -->
        <section class="section">
            <h3>Assignments</h3>
            <div class="tabs">
                <div class="tab active" onclick="switchTab('pending')">Pending</div>
                <div class="tab" onclick="switchTab('completed')">Completed</div>
            </div>
    
            <div id="pending" class="tab-content">
                <ul>
                    {% for item in course_progress_data %}
                    <li class="enrolled-courses">
                        <a class="assignment" href="{% url 'learning:lesson' course_title=item.course  lesson_order=item.last_accessed_lesson_order %}">
                        Assignment pending for lesson {{ item.last_accessed_lesson.title }} of {{ item.course }}.
                        </a>
                    </li>
                    {% empty %}
                    <li>No pending assignments.</li>
                    {% endfor %}
                </ul>
            </div>
    
            <div id="completed" class="tab-content" style="display:none;">
                <table>
                    <thead>
                        <tr>
                            <th>Handed in on</th>
                            <th>Assignment</th>
                            <th>Grade</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in course_progress_data %}
                            {% for a in item.completed_assignments %}
                            <tr>
                                <td>{{ a.date_handed_in|date:"Y-m-d" }}</td> 
                                <td>You handed in assignment for {{ a.lesson }}</td>
                                <td>{{ a.grade|default:"-" }}</td> <!-- Displaying grade or "-" if none -->
                            </tr>
                            {% endfor %}
                        {% empty %}
                        <tr>
                            <td colspan="3">Complete your first assignment to see it here!</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>                
            </div>
        </section>
    
        <!-- Grade Overview Section -->
        <section class="section">
            <h3>Grade Overview</h3>
            <table>
                <thead>
                    <tr>
                        <th>Course</th>
                        <th>Average Grade</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in course_progress_data %}
                    <tr>
                        <td>{{ item.course }}</td>
                        <td>{{ item.average_grade }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
    </div>
{% endblock %}
</html>