capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('teaching/', include(('teaching.urls', 'teaching'), namespace='teaching')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# # Serve media files in development (DEBUG=False mode)
if not settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# if settings.DEBUG:  # Serve static files in production 
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teaching/urls.py
from rest_framework.routers import DefaultRouter
from .views import *
from django.urls import path, include

router = DefaultRouter()
router.register(r'courses', CourseViewSet, basename='course')
router.register(r'student-assignments', StudentAssignmentViewSet)

urlpatterns = [
    path('api/', include(router.urls)),  # Include all router URLs under "api/"
    path('instructor/dashboard/', InstructorDashboardView.as_view(), name='instructor_dashboard'), 
    path('edit-course/<int:pk>/', CourseEditView.as_view(), name="edit_course"),
    path('edit-lesson/<int:pk>/', LessonEditView.as_view(), name="edit_lesson"),
    path('create-course/', CreateCourseView.as_view(), name='create_course'),
    path('add-lesson/<int:pk>/', AddLessonView.as_view(), name='add_lesson'), # Using pk of a course we're adding a lesson to
    path('lesson/<int:pk>/delete/', DeleteLessonView.as_view(), name='lesson_delete'), # Using pk of a lesson to delete

    path('assignment/<int:pk>/file/', get_assignment_file, name='get_assignment_file'),
    path('create-announcement/', CreateAnnouncementView.as_view(), name='create_announcement'),

]

users/urls.py
from django.urls import path
from users.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', homepage_view, name="homepage"),
    path('accounts/login/', login_view, name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('register/', register, name="register"),
    path('courses/', courses, name='courses'),
    path('course_details/<int:course_id>/', course_details, name="course_details"),
    path('enroll/<int:course_id>/', enroll, name="enroll"),
]

teaching/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from capstone.storage_backends import MediaStorage  # Import custom storage


class User(AbstractUser):
    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    ROLE_CHOICES = (
        ('student', 'Student'),
        ('instructor', 'Instructor'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    

class FieldOfStudy(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Field of Studies"


class Prerequisite(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Course(models.Model):
    # Represents a course that an instructor can create and students can enroll in.
    title = models.CharField(max_length=150)
    description = models.TextField()
    instructor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='courses')
    
    LEVEL_CHOICES = (
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    )
    level = models.CharField(max_length=20, choices=LEVEL_CHOICES, blank=True, null=True)
    field_of_study = models.ForeignKey(FieldOfStudy, on_delete=models.CASCADE, default=1)
    prerequisites = models.ManyToManyField(Prerequisite)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} course"


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=255)
    video_url = models.URLField(blank=True, null=True)
    video_file = models.FileField(storage=MediaStorage(), upload_to='lesson_videos/', blank=True, null=True)
    pdf = models.FileField(storage=MediaStorage(), upload_to='lesson_pdfs/', blank=True, null=True)
    content = models.TextField() 
    order = models.PositiveIntegerField()  # Order of lessons in a course
    homework_requirements = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.title} (Order: {self.order}, Course: {self.course.title})"  
    

class Enrollment(models.Model):
    student = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='enrollments')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrollments')
    date_enrolled = models.DateTimeField(auto_now_add=True)
    progress = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # progress percentage
    completed_lessons = models.ManyToManyField(Lesson, through='LessonCompletion')
    
    def calculate_progress(self):
        # Count completed lessons associated with this Enrollment instance
        completed_lessons = LessonCompletion.objects.filter(enrollment=self).count()
        # Total lessons for the course associated with this Enrollment instance
        total_lessons = self.course.lessons.count()
        
        # Calculate progress
        if total_lessons == 0:
            self.progress = 0
        else:
            self.progress = (completed_lessons / total_lessons) * 100
        
        # Save the progress and return it rounded
        self.save()
        return round(self.progress, 2)
    
    def calculate_average_grade(self):
        # Filter submitted assignment associated with the course and count them
        submitted_assignments = StudentAssignment.objects.filter(course=self.course, student=self.student, handed_in=True)
        amount = submitted_assignments.count()

        # Initialize sum
        total_grade = 0
        
        # Sum the grades of submitted assignments
        for assignment in submitted_assignments:
            if assignment.grade is not None:  # Ensure grade is not None
                total_grade += assignment.grade
        
        # Return the average or 0 if no graded assignments were found
        return round(total_grade / amount, 2) if amount > 0 else 0


    def get_last_accessed_lesson_order(self):
        # Get the last completed lesson, ordered by 'order'
        last_completed = self.completed_lessons.order_by('order').last()

        if last_completed:
            # Try to get the next lesson after the last completed one
            next_lesson = Lesson.objects.filter(course=self.course, order__gt=last_completed.order).order_by('order').first()
            
            if next_lesson:
                return next_lesson.order
            else:
                # All lessons completed, return the order of the last completed lesson
                return last_completed.order
        else:
            # If no lessons have been completed, return the first lesson of the course
            first_lesson = Lesson.objects.filter(course=self.course).order_by('order').first()
            return first_lesson.order if first_lesson else None
        

    def __str__(self):
        return f"{self.student} enrolled in {self.course}."
    

class LessonCompletion(models.Model):
    # Intermediary table that handles the relationship between Enrollment and Lesson models to store metadata about it
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)

class StudentAssignment(models.Model):
    student = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='assignments')
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="assignments")
    file = models.FileField(storage=MediaStorage(), upload_to='assignment_files/')
    handed_in = models.BooleanField(default=False)
    date_handed_in = models.DateTimeField(auto_now_add=True)
    grade = models.IntegerField(null=True, blank=True, validators=[MaxValueValidator(10), MinValueValidator(1)])

    def __str__(self):
        return f"Id: {self.id}, Grade: {self.grade}"



#----------- QUIZ RELATED MODELS ---------------#

class Quiz(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quizzes', null=True, blank=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=70)
    difficulty = models.CharField(max_length=10, choices=[('easy', 'Easy'),
                                                          ('medium', 'Medium'),
                                                          ('hard', 'Hard'),])
    number_of_questions = models.PositiveIntegerField()
    time = models.PositiveIntegerField() # Duration of the quiz in minutes
    required_score = models.IntegerField() # Required score to pass the quiz in %

    def __str__(self):
        return self.name
    
    def get_questions(self):
        return self.question_set.all()
    
    class Meta:
        verbose_name_plural = "Quizzes"

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    image = models.ImageField(upload_to='quiz_images/', blank=True, null=True)
    question_order = models.PositiveIntegerField()

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='options')

    def __str__(self):
        return self.text


class StudentQuizSession(models.Model):
    student = models.ForeignKey(Profile, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    correct_answer_count = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)
    solved_in = models.PositiveIntegerField(default=0) # store in seconds

    def calculate_score(self):
        total_questions = self.quiz.questions.count()
        # Calculate score as a percentage
        score_percentage = (self.correct_answer_count / total_questions) * 100

        # Change the 'passed' flag if needed
        if score_percentage >= self.quiz.required_score:
            self.passed = True
            self.save()

        return round(score_percentage, 2)
    

    def __str__(self):
        student = self.student if self.student else "Unknown Student"
        quiz = self.quiz if self.quiz else "Unknown Quiz"
        return f"{student} - {quiz}"



class StudentAnswer(models.Model):
    session = models.ForeignKey(StudentQuizSession, on_delete=models.CASCADE, related_name="student_answers")
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_answer =  models.CharField(max_length=200, blank=True, null=True, default=None)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return str(self.selected_answer) if self.selected_answer else "No answer selected"
    
class Notification(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="sent_notifications", null=True, blank=True) # Who triggered the notification
    recipient = models.ManyToManyField(Profile, related_name='notifications')  # Who the notification is for

teaching/forms.py
from django import forms
from users.models import Course, Lesson
from django.forms.widgets import ClearableFileInput

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'description', 'level', 'field_of_study', 'prerequisites']

# Change default label name to custom one
class CustomClearableFileInput(ClearableFileInput):
    clear_checkbox_label = "Remove"

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['title', 'order', 'content', 'video_url', 'video_file', 'pdf', 
                  'homework_requirements']
        widgets = {
            'video_file': CustomClearableFileInput(),
            'pdf': CustomClearableFileInput(),
        }

    # Pass the course as a hidden field in the form, since Lesson always belongs to specific course
    def __init__(self, *args, **kwargs):
        course = kwargs.pop('course', None)
        super().__init__(*args, **kwargs)
        if course:
            self.fields['course'].initial = course

        

teaching/templates/teaching/confirm_delete.html
{% extends 'users/layout.html' %}
{% load static %}
{% block body %}
    <div class="delete-confirmation">
        <h2>Are you sure you want to delete "{{ object.title }}"?</h2>
        <p>This action cannot be undone.</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes, delete</button>
            <a href="{% url 'teaching:edit_course' object.course.id %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

teaching/templates/teaching/course_edit.html
{% extends 'users/layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Course</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}">
    <link rel="stylesheet" href="{% static 'teaching_styles.css' %}"> 
 
    {% endblock %}
</head>

{% block body %}
    <div class="courses-header">
        <h1 class="header">Edit Course</h1>
    </div>
    
    <div class="container">
        <span class="flex">
            <h2 class="h2-course">Course Info</h2>
            <a href="#" id="edit-button">Edit</a>
        </span>

        <div id="course-display" style="display: block;">
            <div class="info">
                <strong>Title:</strong> <span id="course-title">{{ course.title }}</span>
            </div>
            <div class="info">
                <strong>Description:</strong> <span id="course-description">{{ course.description }}</span>
            </div>
            <div class="info">
                <strong>Level:</strong> <span id="course-level">{{ course.get_level_display }}</span>
            </div>
        </div>

        <!-- Hidden Edit Form -->
        <form id="course-edit" data-course-id="{{ course.id }}" data-api="true" style="display: none;">
            {% csrf_token %}
            <div class="row">
                <div class="first-col">
                    <div class="form-group">
                        {{ form.title.label_tag }}
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        {{ form.description.label_tag }}
                        {{ form.description }}
                    </div>
                </div>
                <div class="second-col">
                    <div class="form-group">
                        {{ form.level.label_tag }}
                        {{ form.level }}
                    </div>
                    <button type="button" id="save-course-changes">Save Changes</button>
                </div>
            </div>
            
        </form>

        <span class="flex">
            <h2 class="h2-lessons">Lessons</h2>
            <a id="add-lesson" href="{% url 'teaching:add_lesson' course.id %}">Add New Lesson</a>
        </span>
        <div class="lessons-section">
            {% for lesson in lessons %}
            <div class="lesson-card">
                <h3>{{ lesson.order }}. {{ lesson.title }}</h3>
                <div class="actions">
                    <a href="{% url 'teaching:edit_lesson' lesson.id %}" class="btn edit-btn">Detailed edit</a>
                   <a href="{% url 'teaching:lesson_delete' lesson.id %}" class="btn delete-btn">Delete</a>
                </div>
            </div>
            {% empty %}
            <p>No lessons available. Add one below!</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}
</html>

teaching/templates/teaching/instructor_dashboard.html
{% extends 'users/layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instructor's Dashboard</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}">
    <link rel="stylesheet" href="{% static 'teaching_styles.css' %}"> 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.16.105/pdf.min.js"></script> 
    {% endblock %}
</head>

{% block body %}
    <div class="courses-header">
        <h1 class="header">Instructor's Dashboard</h1>
    </div>
    <div class="container">

        <section class="section">
            <h3> Courses You Teach </h3>
                <ul>
                {% for course in courses_info %}
                    <li class="enrolled-courses padding">
                        <div class="course-info">
                            <span>{{ course.course.title }}</span>
                        </div>

                        <div class="progress-info">
                            <div class="progress-bar-container">
                            </div>
                            <span class="progress-text">{{ course.students_enrolled }} students enrolled</span>
                        </div>

                        <div class="last-accessed">
                                <a href="{% url 'teaching:edit_course' pk=course.course.pk %}">
                                    Edit course
                                </a>
                        </div>
                    </li>
                {% endfor %}
                </ul>
                <a id="underline" href="{% url 'teaching:create_course' %}">Create new course</a>
        </section>

    <!-- Assignments Section -->
<section class="section assignments">
    <h3>Submitted Assignments</h3>

    <!-- Tabs for Graded and Ungraded -->
    <div class="main">
        <div class="tabs">
            <div class="tab active" onclick="switchTab('ungraded')">Ungraded</div>
            <div class="tab" onclick="switchTab('graded')">Graded</div>
        </div>

        <!-- Course Filter Dropdown -->
        <span class="dropdown">
            <label for="course-filter">Select a Course:</label>
            <select id="course-filter" onchange="filterAssignments()">
                <option value="all">All Courses</option>
                {% for course in course_progress_data %}
                <option value="{{ course.id }}">{{ course.title }}</option>
                {% endfor %}
            </select>
        </span>
    </div>

    <!-- Ungraded Assignments -->
    <div id="ungraded" class="tab-content active">
        <ul id="ungraded-assignments">
            {% for course in course_progress_data %}
            {% for a in course.ungraded_assignments %}
            <li class="assignment-card course-{{ course.id }}" data-assignment-id="{{ a.id }}">
                <div class="flex-assignment">

                    <div class="title-assignment">
                        <span class="assignment-title">{{ a.student }} for lesson {{a.lesson.order}}</span>
                        <span class="submission-date">Submitted on: {{ a.date_handed_in|date:"Y-m-d H:i" }}</span>
                    </div>

                    <div class="download">
                        <a href="javascript:void(0);" id="view-pdf-btn" class="view-pdf-button" data-assignment-id="{{ a.id }}">
                            View PDF
                        </a>
                        <div id="pdf-container" style="display: none;"></div>
                        <a class="grade-button">Grade</a>
                        <input type="number" class="grade-input" min="0" max="10" style="display:none;" />
                        <button class="save-grade-button" style="display:none;">Save Grade</button>
                    </div>

                </div>
            </li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>

    <!-- Graded Assignments -->
    <div id="graded" class="tab-content" style="display:none;">
        <table id="graded-assignments">
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Assignment</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                {% for course in course_progress_data %}
                {% for a in course.graded_assignments %}
                <tr class="course-{{ course.id }}">
                    <td>{{ a.student }}</td>
                    <td>For lesson {{ a.lesson.order }}</td>
                    <td>{{ a.grade|default:"-" }}</td>
                </tr>
                {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    </section>


    <section class="section">
        <div class="notification-header">
            <h3 class="notif">Share Announcement for Course:</h3>
        </div>
        <div class="announcement">
            <form method="post" action="{% url 'teaching:create_announcement' %}" id="announcement-form">
                {% csrf_token %}
                <label for="recipients">Send to:</label>
                <select name="recipients" id="recipients">

                    <option value="all">All Students</option>
                    {% for course in course_progress_data %}
                        <option value="{{ course.id }}">{{ course.title }}</option>
                    {% endfor %}
                </select>
            
                <label for="message">Announcement Message:</label>
                <textarea name="message" id="message" required></textarea>
            
                <button type="submit">Send Announcement</button>
            </form>
        </div>
    </section>
    </div>    
{% endblock %}
</html>

teaching/templates/teaching/lesson_edit.html
{% extends 'users/layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Lesson</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}">
    <link rel="stylesheet" href="{% static 'teaching_styles.css' %}"> 
 
    {% endblock %}
</head>

{% block body %}
    <div class="courses-header">
        <h1 class="header">Edit Lesson</h1>
    </div>
    <div class="container">
        <form method="POST" action="{% url 'teaching:edit_lesson' lesson.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
            <div class="first-col">
            <div class="form-group">
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div class="form-group">
                {{ form.order.label_tag }}
                {{ form.order }}
            </div>
            <div class="form-group">
                {{ form.content.label_tag }}
                {{ form.content }}
            </div>
        </div>
        <div class="second-col">
            <div class="form-group">
                {{ form.video_url.label_tag }}
                {{ form.video_url }}
            </div>
            <div class="form-group">
                {{ form.video_file.label_tag }}
                {{ form.video_file }}
            </div>
            <div class="form-group">
                {{ form.pdf.label_tag }}
                {{ form.pdf }}
            </div>
            <div class="form-group">
                {{ form.homework_requirements.label_tag }}
                {{ form.homework_requirements }}
            </div>
        </div>
    </div>
            <button type="submit" class="btn primary-btn">Save Changes</button>
        </form>
    
    </div>
{% endblock %}
</html>

teaching/templates/teaching/new_course.html
{% extends 'users/layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Course</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}">
    <link rel="stylesheet" href="{% static 'teaching_styles.css' %}"> 
 
    {% endblock %}
</head>

{% block body %}
    <div class="courses-header">
        <h1 class="header">Create New Course</h1>
    </div>
    <div class="container">
        <form id="create-course-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div class="form-group">
                {{ form.description.label_tag }}
                {{ form.description }}
            </div>
            <div class="form-group">
                {{ form.level.label_tag }}
                {{ form.level }}
            </div>
            <div class="form-group">
                {{ form.field_of_study.label_tag }}
                {{ form.field_of_study }}
            </div>
            <button type="submit" id="create-course-btn" class="btn primary-btn">Create Course</button>
        </form>
    
    </div>
{% endblock %}
</html>

teaching/templates/teaching/new_lesson.html
{% extends 'users/layout.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Lesson</title>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'learning_styles.css' %}">
    <link rel="stylesheet" href="{% static 'teaching_styles.css' %}"> 
 
    {% endblock %}
</head>

{% block body %}
    <div class="courses-header">
        <h1 class="header">Add New Lesson</h1>
    </div>

    <!--Error messages-->
    {% if message %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endif %}

    <div class="container">
        <form id="add-lesson-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="first-col">
                    <div class="form-group">
                        {{ form.title.label_tag }}
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        {{ form.order.label_tag }}
                        {{ form.order }}
                    </div>
                    <div class="form-group">
                        {{ form.content.label_tag }}
                        {{ form.content }}
                    </div>
                </div>
            <div class="second-col">
                <div class="form-group">
                    {{ form.video_url.label_tag }}
                    {{ form.video_url }}
                </div>
                <div class="form-group">
                    {{ form.video_file.label_tag }}
                    {{ form.video_file }}
                </div>
                <div class="form-group">
                    {{ form.pdf.label_tag }}
                    {{ form.pdf }}
                </div>
                <div class="form-group">
                    {{ form.homework_requirements.label_tag }}
                    {{ form.homework_requirements }}
                </div>
            </div>
        </div>
            <button type="submit" id="add-lesson-btn" class="btn primary-btn">Add Lesson</button>
        </form>
    
    </div>
{% endblock %}
</html>