capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('learning/', include(('learning.urls', 'learning'), namespace='learning')),
    path('teaching/', include(('teaching.urls', 'teaching'), namespace='teaching')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# # Serve media files in development (DEBUG=False mode)
if not settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# if settings.DEBUG:  # Serve static files in production 
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

learning/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('student/dashboard/', StudentDashboardView.as_view(), name='student_dashboard'),

    path('quizzes/', QuizListView.as_view(), name='quizzes'),
    path('quiz-start/<int:quiz_id>/', QuizStartView.as_view(), name='quiz_start'),
    path('quiz-question/<int:quiz_id>/<int:question_order>/', QuizQuestionView.as_view(), name='quiz_question'),
    path('quiz-complete/<int:quiz_id>/', QuizCompleteView.as_view(), name='quiz_complete'),
    path('quiz-finalize/<int:quiz_id>/', FinalizeQuizView.as_view(), name='quiz_finalize'),

    path('new-notifications-count/', NewNotifCount.as_view(), name="new_notif_count"),
    path('mark-notifications-read/', MarkNotificationsRead.as_view(), name="mark_notifs_read"),
    path('notifications/', Notifications.as_view(), name='notifications'),
    
    path('lesson/<str:course_title>/<int:lesson_order>/', LessonView.as_view(), name='lesson'),
]

teaching/urls.py
from rest_framework.routers import DefaultRouter
from .views import *
from django.urls import path, include

router = DefaultRouter()
router.register(r'courses', CourseViewSet, basename='course')
router.register(r'student-assignments', StudentAssignmentViewSet)

urlpatterns = [
    path('api/', include(router.urls)),  # Include all router URLs under "api/"
    path('instructor/dashboard/', InstructorDashboardView.as_view(), name='instructor_dashboard'), 
    path('edit-course/<int:pk>/', CourseEditView.as_view(), name="edit_course"),
    path('edit-lesson/<int:pk>/', LessonEditView.as_view(), name="edit_lesson"),
    path('create-course/', CreateCourseView.as_view(), name='create_course'),
    path('add-lesson/<int:pk>/', AddLessonView.as_view(), name='add_lesson'), # Using pk of a course we're adding a lesson to
    path('lesson/<int:pk>/delete/', DeleteLessonView.as_view(), name='lesson_delete'), # Using pk of a lesson to delete

    path('assignment/<int:pk>/file/', get_assignment_file, name='get_assignment_file'),
    path('create-announcement/', CreateAnnouncementView.as_view(), name='create_announcement'),

]

users/urls.py
from django.urls import path
from users.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', homepage_view, name="homepage"),
    path('accounts/login/', login_view, name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('register/', register, name="register"),
    path('courses/', courses, name='courses'),
    path('course_details/<int:course_id>/', course_details, name="course_details"),
    path('enroll/<int:course_id>/', enroll, name="enroll"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from capstone.storage_backends import MediaStorage  # Import custom storage


class User(AbstractUser):
    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    ROLE_CHOICES = (
        ('student', 'Student'),
        ('instructor', 'Instructor'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    

class FieldOfStudy(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Field of Studies"


class Prerequisite(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Course(models.Model):
    # Represents a course that an instructor can create and students can enroll in.
    title = models.CharField(max_length=150)
    description = models.TextField()
    instructor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='courses')
    
    LEVEL_CHOICES = (
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    )
    level = models.CharField(max_length=20, choices=LEVEL_CHOICES, blank=True, null=True)
    field_of_study = models.ForeignKey(FieldOfStudy, on_delete=models.CASCADE, default=1)
    prerequisites = models.ManyToManyField(Prerequisite)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} course"


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=255)
    video_url = models.URLField(blank=True, null=True)
    video_file = models.FileField(storage=MediaStorage(), upload_to='lesson_videos/', blank=True, null=True)
    pdf = models.FileField(storage=MediaStorage(), upload_to='lesson_pdfs/', blank=True, null=True)
    content = models.TextField() 
    order = models.PositiveIntegerField()  # Order of lessons in a course
    homework_requirements = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.title} (Order: {self.order}, Course: {self.course.title})"  
    

class Enrollment(models.Model):
    student = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='enrollments')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrollments')
    date_enrolled = models.DateTimeField(auto_now_add=True)
    progress = models.DecimalField(max_digits=5, decimal_places=2, default=0)  # progress percentage
    completed_lessons = models.ManyToManyField(Lesson, through='LessonCompletion')
    
    def calculate_progress(self):
        # Count completed lessons associated with this Enrollment instance
        completed_lessons = LessonCompletion.objects.filter(enrollment=self).count()
        # Total lessons for the course associated with this Enrollment instance
        total_lessons = self.course.lessons.count()
        
        # Calculate progress
        if total_lessons == 0:
            self.progress = 0
        else:
            self.progress = (completed_lessons / total_lessons) * 100
        
        # Save the progress and return it rounded
        self.save()
        return round(self.progress, 2)
    
    def calculate_average_grade(self):
        # Filter submitted assignment associated with the course and count them
        submitted_assignments = StudentAssignment.objects.filter(course=self.course, student=self.student, handed_in=True)
        amount = submitted_assignments.count()

        # Initialize sum
        total_grade = 0
        
        # Sum the grades of submitted assignments
        for assignment in submitted_assignments:
            if assignment.grade is not None:  # Ensure grade is not None
                total_grade += assignment.grade
        
        # Return the average or 0 if no graded assignments were found
        return round(total_grade / amount, 2) if amount > 0 else 0


    def get_last_accessed_lesson_order(self):
        # Get the last completed lesson, ordered by 'order'
        last_completed = self.completed_lessons.order_by('order').last()

        if last_completed:
            # Try to get the next lesson after the last completed one
            next_lesson = Lesson.objects.filter(course=self.course, order__gt=last_completed.order).order_by('order').first()
            
            if next_lesson:
                return next_lesson.order
            else:
                # All lessons completed, return the order of the last completed lesson
                return last_completed.order
        else:
            # If no lessons have been completed, return the first lesson of the course
            first_lesson = Lesson.objects.filter(course=self.course).order_by('order').first()
            return first_lesson.order if first_lesson else None
        

    def __str__(self):
        return f"{self.student} enrolled in {self.course}."
    

class LessonCompletion(models.Model):
    # Intermediary table that handles the relationship between Enrollment and Lesson models to store metadata about it
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)

class StudentAssignment(models.Model):
    student = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='assignments')
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="assignments")
    file = models.FileField(storage=MediaStorage(), upload_to='assignment_files/')
    handed_in = models.BooleanField(default=False)
    date_handed_in = models.DateTimeField(auto_now_add=True)
    grade = models.IntegerField(null=True, blank=True, validators=[MaxValueValidator(10), MinValueValidator(1)])

    def __str__(self):
        return f"Id: {self.id}, Grade: {self.grade}"



#----------- QUIZ RELATED MODELS ---------------#

class Quiz(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quizzes', null=True, blank=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=70)
    difficulty = models.CharField(max_length=10, choices=[('easy', 'Easy'),
                                                          ('medium', 'Medium'),
                                                          ('hard', 'Hard'),])
    number_of_questions = models.PositiveIntegerField()
    time = models.PositiveIntegerField() # Duration of the quiz in minutes
    required_score = models.IntegerField() # Required score to pass the quiz in %

    def __str__(self):
        return self.name
    
    def get_questions(self):
        return self.question_set.all()
    
    class Meta:
        verbose_name_plural = "Quizzes"

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    image = models.ImageField(upload_to='quiz_images/', blank=True, null=True)
    question_order = models.PositiveIntegerField()

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='options')

    def __str__(self):
        return self.text


class StudentQuizSession(models.Model):
    student = models.ForeignKey(Profile, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    correct_answer_count = models.IntegerField(default=0)
    passed = models.BooleanField(default=False)
    solved_in = models.PositiveIntegerField(default=0) # store in seconds

    def calculate_score(self):
        total_questions = self.quiz.questions.count()
        # Calculate score as a percentage
        score_percentage = (self.correct_answer_count / total_questions) * 100

        # Change the 'passed' flag if needed
        if score_percentage >= self.quiz.required_score:
            self.passed = True
            self.save()

        return round(score_percentage, 2)
    

    def __str__(self):
        student = self.student if self.student else "Unknown Student"
        quiz = self.quiz if self.quiz else "Unknown Quiz"
        return f"{student} - {quiz}"



class StudentAnswer(models.Model):
    session = models.ForeignKey(StudentQuizSession, on_delete=models.CASCADE, related_name="student_answers")
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_answer =  models.CharField(max_length=200, blank=True, null=True, default=None)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return str(self.selected_answer) if self.selected_answer else "No answer selected"
    
class Notification(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="sent_notifications", null=True, blank=True) # Who triggered the notification
    recipient = models.ManyToManyField(Profile, related_name='notifications')  # Who the notification is for

users/forms.py
from django import forms
from .models import FieldOfStudy

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
        'placeholder': 'Username', 'class': 'form-control', 'required': True
    }))
    first_name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
        'placeholder': 'First name', 'class': 'form-control', 'required': True
    }))
    last_name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
        'placeholder': 'Last name', 'class': 'form-control', 'required': True
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email', 'class': 'form-control', 'required': True
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password', 'class': 'form-control', 'required': True
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password', 'class': 'form-control', 'required': True
    }))
    role = forms.ChoiceField(choices=[('student', 'Student'), ('instructor', 'Instructor')],
                             widget=forms.RadioSelect(attrs={
                                 'class': 'form-group', 'required': True
                             }))

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data
    

class CourseFilterForm(forms.Form):
    LEVEL_CHOICES = (
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    )
    level = forms.MultipleChoiceField(
        choices=LEVEL_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        required=False  # Allow no selection
    )

    field_of_study = forms.ModelMultipleChoiceField(
        queryset=FieldOfStudy.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False  # Allow no selection
    )

users/templates/users/course_details.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}

{% block body %}
    <div class="courses-header">
        <h1>Course Details</h1>
    </div>

    {% if message %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endif %}

    <main class="course-details-container">
        <!-- Course Overview Section -->
        <section class="course-header">
            <h2>Course: {{ course.title }}</h2>
            <p><strong>Instructor:</strong> {{ course.instructor.first_name }} {{ course.instructor.last_name }}</p>
            <p><strong>Level:</strong> {{ course.level|title }}</p>
            <p><strong>Field of Study:</strong> {{ course.field_of_study }} </p>
            <p><strong>Number of Lessons:</strong> {{ lessons.count }}</p>


            {% if is_enrolled %}
                <button class="enrolled-btn" >Already Enrolled</button>
            {% else %}
                <form  id="enroll-form" method="POST" 
                data-course-title="{{ course.title }}" data-course-id="{{ course.id }}">
                    {% csrf_token %}
                    <button type="submit"  class="enroll-btn">Enroll Now</button>
                </form>
            {% endif %}
        </section>

        <!-- Description Section -->
        <section class="course-prerequisites">
            <h3>Course Description</h3>
            <ul>
                <div>{{ course.description }}</div>
            </ul>
        </section>

        <!-- Syllabus Section -->
        <section class="course-syllabus">
            <h3>Course Syllabus</h3>
            <ul>
                {% for lesson in lessons %}
                <li>Lesson {{ lesson.order }}. {{ lesson.title }}</li>
                {% endfor %}
            </ul>
        </section>

        <!-- Prerequisites Section -->
        <section class="course-prerequisites">
            <h3>Prerequisites</h3>
            <ul>
                {% for p in course.prerequisites.all %}
                    <li>{{ p.name }}</li>
                {% endfor %}
            </ul>
        </section>

        <!-- Progress Tracker (For Enrolled Students) -->
         {% if is_enrolled %}
        <section class="progress-tracker">
            <h3>Your Progress</h3>
            <div class="progress-bar">
                <div class="progress" style="width: {{ progress }}%">{{ progress }}%</div>
            </div>
        </section>
        {% endif %}

        <!-- Instructor Info Section -->
        <section class="instructor-info">
            <h3>Instructor</h3>
            <div class="instructor-card">
                <img src="https://i.pinimg.com/736x/17/fa/44/17fa44e8d7f0d4a341f078b6c94a31ef.jpg" alt="Instructor Picture" class="instructor-img">
                <p><strong>{{ course.instructor.first_name }} {{ course.instructor.last_name }}</strong></p>
                <p>{{ course.instructor.profile.bio }}</p>
            </div>
        </section>

        <!-- Reviews Section -->
        <section class="course-reviews">
            <h3>Student Reviews</h3>
            <div class="review">
                <p><strong>John Smith:</strong> "This course is amazing! I learned so much about Python."</p>
            </div>
            <div class="review">
                <p><strong>Sarah Johnson:</strong> "Great explanations and hands-on examples!"</p>
            </div>
        </section>
    </main>
{% endblock %}

users/templates/users/courses.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}

{% block body %}
<div class="courses-header">
    <h1 class="header">Browse Our Courses</h1>
</div>

<div class="courses-page">
    <!-- Filter Sidebar -->
    <aside class="filter-sidebar">
        <h2>Filter by:</h2>
        <form method="get" id="filter-form">
            {{ form.as_p }}  
            <button type="submit">Filter</button>
        </form>
    </aside>

    <!-- Courses Section -->
    <section class="courses-list">
        {% for course in courses %}
            <div class="course-card">
                <h3 class="course-title">{{ course.title }}</h3>
                <p class="course-category">Field of Study: {{ course.field_of_study}}
                </p>
                <p class="course-teacher">Instructor: {{ course.instructor.first_name }} {{ course.instructor.last_name }}</p>
                <p class="course-description">{{ course.description|truncatechars:150 }}</p>
                <a class="view-details-btn" href="{% url 'users:course_details' course_id=course.id %}">View Details</a>
            </div>
        {% empty %}
            <li>No courses found.</li>
        {% endfor %}
    </section>
</div>
{% endblock %}

users/templates/users/homepage.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Online Learning Platform</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}"> 
    </head>

{% block body %}
    <!-- Hero Section -->
    <section class="hero">
        <div class="container">
            <h2>Learn from the Best</h2>
            <p>Join thousands of students who are enhancing their skills with our diverse course offerings.</p>
            <a href="{% url 'users:courses' %}" class="cta-button">Explore Courses</a>
        </div>
    </section>

    <!-- Featured Courses Section -->
    <section id="courses">
        <div class="container">
            <h2>Featured Courses</h2>
            <div class="course-list">
                {% for course in courses %}
                    <div class="course-item">  
                        <h3>{{ course.title }}</h3>
                        <p class="description">{{ course.description|truncatewords:10 }}</p>
                        <a href="{% url 'users:course_details' course_id=course.id %}" class="course-button">View Course</a>
                    </div>
                {% endfor %}
                <div class="course-item">
                    <h3>Course Title 2</h3>
                    <p class="description">Short description of the course.</p>
                    <a href="#" class="course-button">View Course</a>
                </div>
                <div class="course-item">
                    <h3>Course Title 3</h3>
                    <p class="description">Short description of the course.</p>
                    <a href="#" class="course-button">View Course</a>
                </div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section id="about">
        <div class="container">
            <h2>About Us</h2>
            <div>We are a passionate team of educators and technologists dedicated to creating an accessible, engaging, and high-quality learning experience for everyone.<br>
                 Our platform is built on the belief that education should be available to learners everywhere, regardless of their location or background. <br>
                 Through cutting-edge technology and expertly designed courses, we empower students to achieve their academic and professional goals.<br>
                 Whether you're looking to learn something new, enhance your skills, or explore a new career path, we are here to support you on your journey to success.</div>
        </div>
    </section>

    <!--FAQ section-->
    <section class="faq-section">
        <h2>Frequently Asked Questions</h2>
        <div class="faq-item">
            <button class="faq-question">What is this platform about?</button>
            <div class="faq-answer">
                <p>This platform is an online learning platform where users can enroll in courses, watch lectures, complete assignments, and track their progress.</p>
            </div>
        </div>
        <div class="faq-item">
            <button class="faq-question">How can I enroll in a course?</button>
            <div class="faq-answer">
                <p>You can enroll in a course by registering or logging into your account, navigating to the Courses page, and selecting the course you are interested in.</p>
            </div>
        </div>
        <div class="faq-item">
            <button class="faq-question">Are there any free courses available?</button>
            <div class="faq-answer">
                <p>Yes, we offer a variety of free courses that you can enroll in without any cost. Look for the “Free” label on the course cards.</p>
            </div>
        </div>
    </section>

    <!-- Testimonials Section -->
    <section id="testimonials">
        <div class="container">
            <h2>What Our Students Say</h2>
            <blockquote>
                <p>"This platform has transformed my learning experience!" - James John</p>
            </blockquote>
            <blockquote>
                <p>"The courses are engaging and well-structured." - Alice White</p>
            </blockquote>
        </div>
    </section>


    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            
            <form action="/" method="POST">
                <div class="center-header">
                    <h2 class="contact">Contact Us</h2>
                    <p>If you have any questions left, feel free to reach out!</p>
                </div>
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required>
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
                <label for="message">Message:</label>
                <textarea id="message" name="message" required></textarea>
                <button type="submit">Send Message</button>
            </form>
        </div>
    </section>
{% endblock %}
</html>

users/templates/users/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="csrf-token" content="{{ csrf_token }}">
        <title>Online Learning Platform</title>
        
        <link rel="stylesheet" href="{% static 'styles.css' %}"> 
        {% block styles %}{% endblock %}
        <!-- Icon CDN -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <!-- Bootstrap 5 JS -->
        <!-- <script src="{% static 'main.js' %}"></script> -->
        <script src="{% static 'api_related.js' %}"></script>
        <script script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </head>
    
    <!-- Header Section -->
    <header>
        <div class="nav-container">
            <h1>Online Learning Platform</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'users:homepage' %}">Homepage</a></li>

                    {% if user.is_authenticated %}
                        {% if user.profile.role == 'student' %}
                            <li><a href="{% url 'users:courses' %}">Courses</a></li>
                            <li><a href="{% url 'learning:student_dashboard' %}">My Dashboard</a></li>
                            <li><a href="{% url 'learning:quizzes' %}">My Quizzes</a></li>

                        {% elif user.profile.role == 'instructor' %}
                            <li><a href="{% url 'teaching:instructor_dashboard' %}">Instructor Dashboard</a></li>


                        {% endif %}

                        <li>
                            <form method="POST" action="{% url 'users:logout' %}">
                                {% csrf_token %}
                                <button class="logout-btn" type="submit">Logout</button>
                            </form>
                        </li>

                    {% else %}
                        <li><a href="{% url 'users:courses' %}">Courses</a></li>
                        <li><a href="{% url 'users:homepage' %}#about">About Us</a></li>
                        <li><a href="{% url 'users:homepage' %}#contact">Contact Us</a></li>
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                        <li><a href="{% url 'users:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>

    <body>
    {% block body %}
    {% endblock %}


<!-- Footer Section -->
<footer>
    <div class="footer-container">
        <p>&copy; 2024 Online Learning Platform. All rights reserved.</p>
        <ul>
            <li><a href="{% url 'users:homepage' %}#about">About</a></li>
            <li><a href="{% url 'users:homepage' %}#contact">Contact Us</a></li>
            <li><a href="{% url 'users:courses' %}">Courses</a></li>
        </ul>
    </div>
</footer>
<script src="{% static 'main.js' %}"></script> 
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
{% extends 'users/layout.html' %}

{% block body %}
<body>
    <!--Error messages-->
    {% if message %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endif %}

    <div class="login-register-container">
        <div class="form-wrapper">
            <form id="login-form" class="auth-form" method="POST" action="{% url 'users:login' %}">
                {% csrf_token %}
                <h2>Login</h2>
                <input type="text" name="username" placeholder="Username" required>
                <input type="password" name="password" placeholder="Password" required>
                <button type="submit">Login</button>
                <p>Don't have an account? <a href="{% url 'users:register'%}">Register here</a></p>
            </form>
        </div>
    </div>
    
</body>
{% endblock %}

users/templates/users/register.html
<!DOCTYPE html>
{% extends 'users/layout.html'%}

{% block body%}
<!--Error messages-->
{% if message %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
{% endif %}

<div class="login-register-container">
    <div class="form-wrapper">
        <form id="register-form" class="auth-form" method="POST">
            <h2>Register</h2>
            {% csrf_token %}
            {{ form }}
            <button type="submit">Register</button>
            <p>Already have an account? <a href="{% url 'users:login' %}">Login here</a></p>
        </form>
    </div>
</div>
{% endblock %}